### ISSUE TITLE
这段代码，提示sign不对，能否检查一下，谢谢

### ISSUE THREAD

**Issue by fakers777** [ImSingee/PayJS#3]
c = p.get_cashier_url(out_trade_no=OUT_TRADE_NO, total_fee=TOTAL_FEE, body=BODY, callback_url=CALLBACK_URL, notify_url=NOTIFY_URL, attach=ATTACH)
print(c)

**Comment by a69186005** [comment]
> c = p.get_cashier_url(out_trade_no=OUT_TRADE_NO, total_fee=TOTAL_FEE, body=BODY, callback_url=CALLBACK_URL, notify_url=NOTIFY_URL, attach=ATTACH)
> print(c)

You can check sign.py in the library. The writer missed some codes that if 'auto' =0 and 'hide' =0 , they must be pop
